# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ali Connors
tagline:             'Geek reveries'
description:         'A place where things about software and web development are written. By <a href="http://twitter.com/MonsieurCelsius">Sir Celsius</a>'
url:                 http://aliconnors.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Marc Bramaud du Boucheron
  url:               https://twitter.com/MonsieurCelsius
  email:             m.duboucheron@gmail.com

# Custom vars
version:             1.0.0
metadescription:     'A software and web development blog. By Marc du Boucheron'

# Social vars
github.home:        'https://github.com/sircelsiussexy'
